title: "Mauricio D. Sacchi"
description: "Professor, University of Alberta"

theme: jekyll-theme-minimal
logo: /Photo.png

email: msacchi@ualberta.ca
github_username: msacchi

show_downloads: false

markdown: kramdown
kramdown:
  math_engine: mathjax
