title: "Mauricio D. Sacchi"
description: "Professor of Physics, University of Alberta â€” SAIG"

theme: jekyll-theme-minimal
logo: /portrait.jpg

email: msacchi@ualberta.ca
github_username: msacchi

show_downloads: false

markdown: kramdown
kramdown:
  math_engine: mathjax
